# ============================================================
# VisionAI - Eye Disease Detection System
# SMART - Sanjivani Multidisciplinary AI Research & Technology
# utils/report_generator.py - Generate Patient Report
# ============================================================
#
# CHANGES:
#   1. Report filename now includes timestamp: report_YYYY-MM-DD_HH-MM-SS.txt
#   2. Saves to patient folder directly (no subfolder)
#   3. File write wrapped in try/except — no unhandled crashes
#   4. save_path validated before writing
# ============================================================

import os
from datetime import datetime
from loguru import logger
from ui.styles import DISEASE_INFO


class ReportGenerator:

    def __init__(self):
        logger.info("ReportGenerator initialised")

    def generate(
        self,
        save_path:  str,
        patient_id: str,
        result:     dict,
        model_name: str,
        timestamp:  str = None,
    ) -> str:
        """
        Generate and save patient report as report_TIMESTAMP.txt
        """
        if not os.path.isdir(save_path):
            raise ValueError(f"Report save path does not exist: {save_path}")

        if timestamp is None:
            timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

        report_content = self._build_report(patient_id, result, model_name, timestamp)
        filename       = f"report_{timestamp}.txt"
        report_path    = os.path.join(save_path, filename)

        try:
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(report_content)
        except OSError as e:
            msg = f"Failed to write report to {report_path}: {e}"
            logger.error(msg)
            raise RuntimeError(msg) from e

        logger.info(f"Report saved: {report_path}")
        return report_path

    def _build_report(
        self,
        patient_id: str,
        result:     dict,
        model_name: str,
        timestamp:  str,
    ) -> str:
        disease    = result.get("disease",    "Unknown")
        confidence = result.get("confidence", 0.0)
        top3       = result.get("results",    [])

        info        = DISEASE_INFO.get(disease, {})
        full_name   = info.get("full_name",   disease)
        description = info.get("description", "No description available.")
        symptoms    = info.get("symptoms",    "N/A")
        treatment   = info.get("treatment",   "N/A")
        severity    = info.get("severity",    "N/A")

        line  = "=" * 65
        sline = "-" * 65

        report = f"""
{line}
          VisionAI - Eye Disease Detection Report
    SMART - Sanjivani Multidisciplinary AI Research & Technology
{line}

PATIENT INFORMATION
{sline}
  Patient ID       : {patient_id}
  Date & Time      : {timestamp.replace("_", " ").replace("-", ":")}
  Report Generated : {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

MODEL INFORMATION
{sline}
  Model Used       : {model_name}
  Framework        : PyTorch + timm
  Image Size       : 640 x 640
  Normalization    : ImageNet (mean/std)

DETECTION RESULTS
{sline}
  Detected Disease : {disease}
  Full Name        : {full_name}
  Confidence Score : {confidence:.2f}%
  Severity Level   : {severity}

TOP-3 PREDICTIONS
{sline}"""

        for i, pred in enumerate(top3[:3]):
            bar_len = int(pred["confidence"] / 5)
            bar     = "█" * bar_len + "░" * (20 - bar_len)
            report += f"\n  {i+1}. {pred['class']:<12} {pred['confidence']:>6.2f}%  [{bar}]"

        report += f"""

DISEASE INFORMATION
{sline}
  {description}

SYMPTOMS
{sline}
  {symptoms}

RECOMMENDED TREATMENT
{sline}
  {treatment}

DETECTION SUMMARY
{sline}"""

        if disease == "Normal":
            report += """
  ✓ No eye disease detected.
  ✓ Eye appears healthy based on fundus analysis.
  ✓ Regular eye checkups are recommended.
  ✓ Maintain a healthy lifestyle for good eye health."""
        else:
            report += f"""
  ⚠ Eye disease detected: {disease}
  ⚠ Confidence level: {confidence:.2f}%
  ⚠ Please consult an ophthalmologist immediately.
  ⚠ This report is AI-generated and should not replace
    professional medical diagnosis."""

        report += f"""

DISCLAIMER
{sline}
  This report is generated by VisionAI AI system for
  preliminary screening purposes only. It is NOT a substitute
  for professional medical diagnosis. Always consult a
  qualified ophthalmologist for proper diagnosis and treatment.

{line}
  VisionAI v1.0.0  |  SMART Lab  |  {datetime.now().strftime("%Y")}
  Sanjivani Multidisciplinary AI Research & Technology
{line}
"""
        return report

    def get_summary(self, result: dict) -> str:
        disease    = result.get("disease",    "Unknown")
        confidence = result.get("confidence", 0.0)
        if disease == "Normal":
            return f"✓ Normal eye detected ({confidence:.1f}% confidence)"
        return f"⚠ {disease} detected ({confidence:.1f}% confidence) — consult ophthalmologist"